name: baratito_mobile
description: "Baratito's mobile client"
publish_to: "none"
version: 0.1.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  baratito_ui:
    path: ../baratito_ui/
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.0
  easy_localization_loader: ^1.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/localizations/
