name: baratito_mobile
description: "Baratito's mobile client"
publish_to: "none"
version: 0.1.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_size_text_field: ^1.0.1
  baratito_core:
    path: ../baratito_core/
  baratito_ui:
    path: ../baratito_ui/
  cached_network_image: ^3.1.0+1
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.0
  easy_localization_loader: ^1.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_polyline_points: ^1.0.0
  flutter_svg: ^0.23.0+1
  get_it: ^7.2.0
  google_maps_flutter: ^2.1.0
  google_maps_webservice: ^0.0.19
  just_debounce_it: ^4.0.0+2
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/localizations/
    - assets/illustrations/products/
    - assets/illustrations/user_locations/
    - assets/illustrations/shopping/
